// Generated by https://quicktype.io

export interface Archivo {
    id:               number;
    construccione_id: string;
    archivo_id:       string;
    nombre:           string;
    tipo:             string;
    link_vista:       string;
    link_actualizada: null;
    link_descargar:   string;
    vista:            string;
    created_at:       string;
    updated_at:       string;
}
