// Generated by https://quicktype.io

export interface Archivo 
{
    createdTime:       string;
    fileExtension:     string;
    fullFileExtension: string;
    mimeType:          string;
    modifiedTime:      string;
    name:              string;
    originalFilename:  string;
    webContentLink:    string;
    webViewLink:       string;
    lastModifyingUser: LastModifyingUser;
}

export interface LastModifyingUser {
    displayName:  string;
    emailAddress: string;
    kind:         string;
    me:           boolean;
    permissionId: string;
    photoLink:    string;
}

export interface Carpeta {
    createdTime:       string;
    fileExtension:     string;
    fullFileExtension: string;
    mimeType:          string;
    modifiedTime:      string;
    name:              string;
    originalFilename:  string;
    webContentLink:    string;
    webViewLink:       string;
    lastModifyingUser: LastModifyingUser;
}


