// Generated by https://quicktype.io

export interface companies {
    id:          number;
    nombre:      string;
    descripcion: string;
    status:      string;
    created_at:  string;
    updated_at:  string;
}
