// Generated by https://quicktype.io

import { Archivo } from "./archivos";

export interface constructions {
    id:         number;
    empresa_id: string;
    nombre:     string;
    codigo:     string;
    link:       string;
    sources:    string;
    status:     string;
    archivos:   Archivo[]
}
