// Generated by https://quicktype.io

export interface constructions {
    id:         number;
    empresa_id: string;
    nombre:     string;
    codigo:     string;
    link:       string;
    status:     string;
}
