// Generated by https://quicktype.io

export class User {
  public id!: number;
  public name!: string;
  public email!: string;
  public status!: string;
  public created_at!: string;
  public updated_at!: string;
  public role!: string;
  }
